sonar.projectKey=EwertonHecsley_node-eduLink
sonar.organization=ewerton-hecsley-dev

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=src/**/*.d.ts,src/**/index.ts,src/**/*.module.ts,src/main.ts,src/core/domain/**/entity/*.ts,src/infra/**/*.ts,src/presentation/**/*.ts,src/shared/**/*.ts